name: annisa_web
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  simple_gesture_detector:
  states_rebuilder: ^6.0.0
  url_strategy: ^0.2.0
  # mock
  firebase_auth_mocks: ^0.8.2
  google_sign_in_mocks: ^0.2.1
  firebase_storage_mocks: ^0.5.0
  fake_cloud_firestore: ^1.2.1
  #
  firebase_core: ^1.10.5
  firebase_analytics: ^9.0.3
  #
  cloud_firestore: ^3.1.4
  cloud_firestore_web: ^2.6.4
  firebase_auth: ^3.3.3
  firebase_auth_web: ^3.3.4
  google_fonts: ^2.3.1
  google_sign_in: ^5.2.1
  google_sign_in_web: ^0.10.0+3
  firebase_storage: ^10.2.4
  firebase_storage_web: ^3.2.5
  #
  flutter_riverpod:
  connectivity:
  get:
  get_storage:
  intl:
  keyboard_dismisser:
  fluttertoast:
  english_words:
  transparent_image:
  image_picker:
  shimmer:
  path_provider:
  flutter_fadein:
  logger:
  http:
  dio:
  alice:
  #

  # pkg_master:
  #   path: ./packages/pkg_master
  # pkg_widget_collection:
  #   path: ./packages/pkg_widget_collection

  # pkg_master:
  #   git:
  #     url: https://github.com/nostracode/pkg_master.git
  # pkg_widget_collection:
  #   git:
  #     url: https://github.com/nostracode/pkg_widget_collection.git

  # # * import package from git repo
  # <package-name>:
  #   git:
  #     url: <git-url>
  #   ref: <branch-on-git>
  #   path: <path/to/pkg_master>

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/env/
    - assets/json/
    - assets/fonts/
    - assets/icons/
    - assets/images/
  fonts:
    - family: Newsreader
      fonts:
        - asset: assets/fonts/Newsreader-Regular.ttf
        - asset: assets/fonts/Newsreader-Italic.ttf
          style: italic
        - asset: assets/fonts/Newsreader-Bold.ttf
          weight: 700
#
# * TO DO list for new project
#
# * 1. rename project and bundleID
# https://pub.dev/packages/rename
# -> don't use underscore will give error, use '-' instead of '_'
# dart pub global activate rename
# dart pub global run rename --bundleId com.nostracode.fe_master --target android
# dart pub global run rename --bundleId com.nostracode.fe-master --target ios
# dart pub global run rename --bundleId com.nostracode.fe-master --target macOS
# dart pub global run rename --appname "FE Master"
#
# * 2. connect to firebase
# -> add new project at firebase before run below commands
# -> for first config we don't need "google-services.json" anymore
# flutter pub add firebase_core => (if needed)
# dart pub global activate flutterfire_cli
# flutterfire configure
#
# * 3. add fingerprint to firebase  (android)
# -> generate sha1 & sha256 before download google-services.json file
# -> on mac run this command on terminal
# keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android
#
# * 3. google-services.json (android)
# -> add fingerprint sha1 on project settings (android)
# -> download google-services.json put it at folder_project/android/app
#
# * 4. fixing on configuration platform files  (android)
# ext.kotlin_version = '1.6.10'                         //! Add this line on android/build.gradle
# classpath 'com.google.gms:google-services:4.3.10'     //! Add this line on android/build.gradle
# apply plugin: 'com.google.gms.google-services'        //! Add this line on android/app/build.gradle
# minSdkVersion 19                                      //! Add this line on android/app/build.gradle
# targetSdkVersion 30                                   //! Add this line on android/app/build.gradle
# compileSdkVersion localProperties.getProperty('flutter.compileSdkVersion').toInteger()    //! Add this line on android/app/build.gradle
# minSdkVersion localProperties.getProperty('flutter.minSdkVersion').toInteger()            //! Add this line on android/app/build.gradle
# targetSdkVersion localProperties.getProperty('flutter.targetSdkVersion').toInteger()      //! Add this line on android/app/build.gradle
# multiDexEnabled true                                  //! Add this line on android/app/build.gradle
# flutter.compileSdkVersion=31                          //! add this line on local.properties
# flutter.minSdkVersion=21                              //! add this line on local.properties
# flutter.targetSdkVersion=31                           //! add this line on local.properties
#
# * 5. create launch.json file for "run and debug" configuration
# -> create launch.json file for "run and debug" configuration
# -> add dev,stage,prod configuration
#
# * 6. fixing on configuration platform files  (ios)
# platform :ios, '10.0'                                 //! Add this line on ios/Podfile
# platform :osx, '10.12'                                //! Add this line on macos/Podfile
